[package]
name = "nixdoc"
version = "1.0.1"
authors = ["Vincent Ambo <mail@tazj.in>"]

[dependencies]
xml-rs = "0.8"
structopt = "0.2"
failure = "0.1"

[dependencies.rnix]
git = "https://gitlab.com/jD91mZM2/rnix.git"
branch = "rowan"

[dependencies.rowan]
git = "https://github.com/matklad/rowan.git"
